
package e2s;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "E2SoapInterfacePortType", targetNamespace = "http://tempuri.org/e2.xsd/E2SoapInterface.wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface E2SoapInterfacePortType {


    /**
     * Service definition of function e2__GetPropertyInfo
     * 
     * @param propIdArr
     * @return
     *     returns java.util.List<e2s.PropertyInfo>
     */
    @WebMethod(operationName = "GetPropertyInfo")
    @WebResult(name = "data", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "GetPropertyInfo", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetPropertyInfo")
    @ResponseWrapper(localName = "GetPropertyInfoResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetPropertyInfoResponse")
    public List<PropertyInfo> getPropertyInfo(
        @WebParam(name = "propIdArr", targetNamespace = "http://tempuri.org/e2.xsd")
        PropIdArr propIdArr);

    /**
     * Service definition of function e2__GetPropertyExpandedStatus
     * 
     * @param propIdArr
     * @return
     *     returns java.util.List<e2s.PropertyExpandedStatus>
     */
    @WebMethod(operationName = "GetPropertyExpandedStatus")
    @WebResult(name = "data", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "GetPropertyExpandedStatus", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetPropertyExpandedStatus")
    @ResponseWrapper(localName = "GetPropertyExpandedStatusResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetPropertyExpandedStatusResponse")
    public List<PropertyExpandedStatus> getPropertyExpandedStatus(
        @WebParam(name = "propIdArr", targetNamespace = "http://tempuri.org/e2.xsd")
        PropIdArr propIdArr);

    /**
     * Service definition of function e2__GetPropertyConfigValue
     * 
     * @param propIdArr
     * @return
     *     returns java.util.List<e2s.PropertyValue>
     */
    @WebMethod(operationName = "GetPropertyConfigValue")
    @WebResult(name = "data", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "GetPropertyConfigValue", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetPropertyConfigValue")
    @ResponseWrapper(localName = "GetPropertyConfigValueResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetPropertyConfigValueResponse")
    public List<PropertyValue> getPropertyConfigValue(
        @WebParam(name = "propIdArr", targetNamespace = "http://tempuri.org/e2.xsd")
        PropIdArr propIdArr);

    /**
     * Service definition of function e2__SetPropertyConfigValue
     * 
     * @param propValueArray
     * @return
     *     returns java.util.List<e2s.PropertyStatus>
     */
    @WebMethod(operationName = "SetPropertyConfigValue")
    @WebResult(name = "data", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "SetPropertyConfigValue", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.SetPropertyConfigValue")
    @ResponseWrapper(localName = "SetPropertyConfigValueResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.SetPropertyConfigValueResponse")
    public List<PropertyStatus> setPropertyConfigValue(
        @WebParam(name = "propValueArray", targetNamespace = "http://tempuri.org/e2.xsd")
        PropertyValueArray propValueArray);

    /**
     * Service definition of function e2__OverridePropertyValue
     * 
     * @param time
     * @param propId
     * @param value
     * @param enable
     * @param type
     * @return
     *     returns int
     */
    @WebMethod(operationName = "OverridePropertyValue")
    @WebResult(name = "resultValue", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "OverridePropertyValue", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.OverridePropertyValue")
    @ResponseWrapper(localName = "OverridePropertyValueResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.OverridePropertyValueResponse")
    public int overridePropertyValue(
        @WebParam(name = "propId", targetNamespace = "http://tempuri.org/e2.xsd")
        java.lang.String propId,
        @WebParam(name = "enable", targetNamespace = "http://tempuri.org/e2.xsd")
        boolean enable,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/e2.xsd")
        int type,
        @WebParam(name = "time", targetNamespace = "http://tempuri.org/e2.xsd")
        java.lang.String time,
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/e2.xsd")
        java.lang.String value);

    /**
     * Service definition of function e2__GetPropertyLog
     * 
     * @param propId
     * @return
     *     returns java.util.List<e2s.PropertyLogEntry>
     */
    @WebMethod(operationName = "GetPropertyLog")
    @WebResult(name = "data", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "GetPropertyLog", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetPropertyLog")
    @ResponseWrapper(localName = "GetPropertyLogResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetPropertyLogResponse")
    public List<PropertyLogEntry> getPropertyLog(
        @WebParam(name = "propId", targetNamespace = "http://tempuri.org/e2.xsd")
        java.lang.String propId);

    /**
     * Service definition of function e2__GetAlarmList
     * 
     * @param controller
     * @param filter
     * @return
     *     returns java.util.List<e2s.AlarmInfo>
     */
    @WebMethod(operationName = "GetAlarmList")
    @WebResult(name = "data", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "GetAlarmList", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetAlarmList")
    @ResponseWrapper(localName = "GetAlarmListResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetAlarmListResponse")
    public List<AlarmInfo> getAlarmList(
        @WebParam(name = "controller", targetNamespace = "http://tempuri.org/e2.xsd")
        java.lang.String controller,
        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/e2.xsd")
        boolean filter);

    /**
     * Service definition of function e2__PerformAlarmAction
     * 
     * @param alarmIdArray
     * @param action
     * @param controller
     * @return
     *     returns int
     */
    @WebMethod(operationName = "PerformAlarmAction")
    @WebResult(name = "result", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "PerformAlarmAction", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.PerformAlarmAction")
    @ResponseWrapper(localName = "PerformAlarmActionResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.PerformAlarmActionResponse")
    public int performAlarmAction(
        @WebParam(name = "action", targetNamespace = "http://tempuri.org/e2.xsd")
        int action,
        @WebParam(name = "alarmIdArray", targetNamespace = "http://tempuri.org/e2.xsd")
        AlarmIdArray alarmIdArray,
        @WebParam(name = "controller", targetNamespace = "http://tempuri.org/e2.xsd")
        java.lang.String controller);

    /**
     * Service definition of function e2__GetApplicationList
     * 
     * @param controller
     * @return
     *     returns java.util.List<e2s.ApplicationInfo>
     */
    @WebMethod(operationName = "GetApplicationList")
    @WebResult(name = "data", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "GetApplicationList", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetApplicationList")
    @ResponseWrapper(localName = "GetApplicationListResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetApplicationListResponse")
    public List<ApplicationInfo> getApplicationList(
        @WebParam(name = "controller", targetNamespace = "http://tempuri.org/e2.xsd")
        java.lang.String controller);

    /**
     * Service definition of function e2__GetControllerList
     * 
     * @param controllerType
     * @return
     *     returns java.util.List<e2s.ControllerInfo>
     */
    @WebMethod(operationName = "GetControllerList")
    @WebResult(name = "data", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "GetControllerList", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetControllerList")
    @ResponseWrapper(localName = "GetControllerListResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetControllerListResponse")
    public List<ControllerInfo> getControllerList(
        @WebParam(name = "controllerType", targetNamespace = "http://tempuri.org/e2.xsd")
        int controllerType);

    /**
     * Service definition of function e2__GetThisControllerName
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetThisControllerName")
    @WebResult(name = "controllerName", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "GetThisControllerName", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetThisControllerName")
    @ResponseWrapper(localName = "GetThisControllerNameResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetThisControllerNameResponse")
    public java.lang.String getThisControllerName();

    /**
     * Service definition of function e2__GetThisControllerVersion
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetThisControllerVersion")
    @WebResult(name = "controllerVersion", targetNamespace = "http://tempuri.org/e2.xsd")
    @RequestWrapper(localName = "GetThisControllerVersion", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetThisControllerVersion")
    @ResponseWrapper(localName = "GetThisControllerVersionResponse", targetNamespace = "http://tempuri.org/e2.xsd", className = "e2s.GetThisControllerVersionResponse")
    public java.lang.String getThisControllerVersion();

}
